### ISSUE TITLE
Use semver for new releases

### ISSUE THREAD

**Issue by dreua** [py-vobject/vobject#31]
I am just stumbling over the 4 part versions that the original vobject uses. It just looks very odd to me, may I suggest to go with 3 part versions (major.minor.patch) and semantic versioning for further releases of this project?

**Comment by da4089** [comment]
I'm not sure what the motivation for introducing a 4th digit was, but ...

Going forward, my intention is to use 3-digit semantic versions, with one possible exception.

I'm undecided whether to ship a Python 2.7-compatible v1.0.0 as a successor to the 0.9.x series, with a few accumulated bug fixes and then mark it as a "no new features" branch, and move the Python3-only work to a new v2.x.y series, OR just to leave Python2 in 0.9.x, and make 1.x.y the Python3 version.

The downside of changing to a v1.x.y for the existing code + bugfixes is that people might expect it to have some major new feature(s), and it won't.  It's also possible that some project might have a 0.9.* requirement, and moving to 1.x would break their automatic pip imports.  Overall I think both of these are fairly benign, but others might disagree.

I think I prefer the 1.x for Python2 / 2.x for Python3 route: it seems a little unfair to "steal" the 1.0.0 moniker from the existing codebase, which has been hanging out as a 0.9.x for so long.  It wouldn't be strictly semver at that point: there's no breaking changes contemplated for that version, but I've always seen the 0.x branches as more of an "in development" thing, and it really deserves promotion from there.

Feedback on these plans is very welcome -- what do you think?

**Comment by rsb-23** [comment]
I would suggest `just to leave Python2 in 0.9.x, and make 1.x.y the Python3 version.`

Reason :
- Its been 6 years since last commit to the previous project, so definitely most of the issues have been custom patched by the users or they would have used some workaround.
- Ideally, dependencies are defined to keep it compatible with exact or the latest minor version within a project. So, the expectation is any breaking changes should be a part of major release, not just new features.
- Python2.x may not have much users now.

> We (you) can create a poll under discussion for community to decide.

Hence, for these reasons, we should focus on the majority, put efforts where it has more impact and keep things simple.

<hr/>
🤔 Suppose, we make v1.x as python3. We can start adding deprecation warnings in v1 and by v2 we can remove deprecated code.

**Comment by da4089** [comment]
To summarize:
* vobject will use semver-2.0 in future
    ```
    Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes
    MINOR version when you add functionality in a backward compatible manner
    PATCH version when you make backward compatible bug fixes```

* The current 0.9.z series will remain compatible with Python 2.7
  * Most likely, this branch will get no new features, but if it ever does, it'll become 0.10.z, 0.11.z, etc.
* A future 1.y.z series will support Python 3 only
  * This change will happen soon (mid-2024)
  * I expect to maintain API compatibility for as long as reasonably possible, so a 2.y.z series is possible, but not likely any time soon.
